### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by gqtn** [vinwareznic/hls-analyzer#1]
Hello.

I've tried to use this tool, but I can't because this error:
```
┌─[lab@debian]─[~/hls-analyzer]─[16:29:54]
└──╼ $ python3 hls-analyzer.py https://test/playlist/playlist.m3u8
  File "/home/lab/hls-analyzer/hls-analyzer.py", line 119
    print "{0}".format(track.payloadReader.frames[j].type),
          ^
SyntaxError: invalid syntax
```

Could you help me?

Thank you.

**Comment by jakubvojacek** [comment]
@quintanaplaca  given the age of this repository, it is possible that you might have to use python2x instead of 3. They did some BC breaks in pyhon3

**Comment by gqtn** [comment]
@jakubvojacek, exactly it.
